# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d350a91de705cc0e2a9ca1ee6e3af359860740f2e7986825cd75b9ecf62470ad854f4cf43e7aadf4b0416417eea9d5854f2b3d947c746dfa4ed6da11f416c4f4

test:
  secret_key_base: eb2c66b5d54f858e581ce1ac8073fcc1a5ad28bb29825a924ebe45084a3f0a4789cdd4807d045725fefa90c9b3c19799ec3f6f3a3adf8abd25c5795d30952b87

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
